<?php

/**
 * @file
 * Implements different hook().
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\pragathi_exercise\Event\UserLoginEvent;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_form_alter().
 */
function pragathi_exercise_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Calling theservice.
  $data = \Drupal::service('custom_service')->getName();

  if ($form_id == "node_article_edit_form") {
    $helptext = \Drupal::configFactory()->getEditable("pragathi_exercise.settings")->get("helptext");
    // type: node object.
    $node = \Drupal::routeMatch()->getParameter("node");
    $token_service = \Drupal::token();
    $hlptxt = $token_service->replace($helptext, ['node' => $node], ['clear' => TRUE]);
    $form['#prefix'] = "<span>" . $hlptxt . "</span>";
  }
}

/**
 * Implements hook_theme().
 */
function pragathi_exercise_theme($existing, $type, $theme, $path) {
  // Hook_theme is to create a template.
  return [
    // Template name.
    'controller_template' => [
      // What are all the variables we want to render in the twig template.
      'variables' => [
        'message' => "",
        'hexcode' => "",
      ],
    ],
  ];
}

/**
 * Implements hook_user_login().
 */
function pragathi_exercise_user_login($account) {
  // Instantiate our event.
  $event = new UserLoginEvent($account);
  // Triggering the event_dispatcher service and dispatch the event.
  $event_dispatcher = \Drupal::service('event_dispatcher');
  $event_dispatcher->dispatch($event, UserLoginEvent::EVENT_NAME);
}

/**
 * Implements hook_page_attachments_alter().
 */
function pragathi_exercise_page_attachments_alter(array &$attachments) {
  $attachments['#attached']['library'][] = 'pragathi_exercise/config_lib';
  $attachments['#attached']['drupalSettings']['pragathi_exercise']['testing'] = "testing variable";

  // Calling the service.
  $route_match = \Drupal::routeMatch();
  // Getting the route name of the particular page.
  $route_name = $route_match->getRouteName();
  // print_r($route_name);exit;
  // If the route name matches.
  if ($route_name === 'comment.admin') {
    // Apply the css.
    $attachments['#attached']['library'][] = 'pragathi_exercise/config_lib';
  }
  // If the route name matches.
  elseif ($route_name === 'entity.node.canonical') {
    // Apply the css.
    $attachments['#attached']['library'][] = 'pragathi_exercise/config_lib';
  }
}

/**
 * @file
 * Contains custom_mail.module..
 */

/**
 * Implements hook_help().
 */
function pragathi_exercise_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_mail module.
    case 'help.page.pragathi_exercise':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('custom module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_mail().
 */
function pragathi_exercise_mail($key, &$message, $params) {
  $options = [
    'langcode' => $message['langcode'],
  ];

  switch ($key) {
    case 'create_page':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Page created: @title', ['@title' => $params['node_title']], $options);
      $message['body'][] = $params['message'];
      break;
  }
}

/**
 * Implements hook_entity_insert().
 */
function pragathi_exercise_entity_insert(EntityInterface $entity) {

  if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'page')) {
    return;
  }

  $mailManager = \Drupal::service('plugin.manager.mail');

  $module = 'pragathi_exercise';
  $key = 'create_page';
  $to = \Drupal::currentUser()->getEmail();
  $params['message'] = $entity->get('body')->value;
  $params['node_title'] = $entity->label();
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = TRUE;

  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  if ($result['result'] !== TRUE) {

    \Drupal::messenger()->addMessage(t('There was a problem sending your message and it was not sent'), 'error');
  }
  else {

    \Drupal::messenger()->addMessage(t('Your message has been sent.'), 'status');
  }

}

/**
 * Implements hook_entity_view_alter().
 */
function pragathi_exercise_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() == "node") {
    $build['field_text']['#title'] = "text title changed";
    unset($build['field_date']);
    $build['markup'] = [
      '#markup' => "<h3>Testing the hook</h3>",
    ];
  }

}

/**
 * Implements hook_entity_view().
 */
function pragathi_exercise_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  // Condition entity type = node.
  $session = \Drupal::request()->getSession();
  $counts = $session->get("pragathi_exercise.node_view_count", []);
  if (!isset($counts[$entity->id()])) {
    $counts[$entity->id()] = 1;
  }
  else {
    $counts[$entity->id()]++;
  }

  $session->set("pragathi_exercise.node_view_count", $counts);
  $build['count'] = [
    '#markup' => "Viewed " . $counts[$entity->id()] . " times",
    '#cache' => [
      'max-age' => 0,
    ],
  ];

}

/**
 * Implements hook_entity_presave().
 */
function pragathi_exercise_entity_presave(EntityInterface $entity) {
  if ($entity->getEntityTypeId() == "node") {
    $entity->set("title", "entity presaving the values");
  }
}
